- src: https://cdn.polyfill.io/v3/polyfill.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  noModule: true
  defer: true
- src: https://unpkg.com/@webcomponents/custom-elements@1.4.2/custom-elements.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  noModule: true
  defer: true
  integrity: sha384-xyhN4T4+9VPh8uXl6uWjGzsqwNXN9C2tla8b6zSrSqYlMFUoeCdoxiEJU0js+GNE
- src: https://unpkg.com/@shgysk8zer0/polyfills@0.0.5/all.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  integrity: sha384-xoY6kDRPTvbDfGdGA3S6Ercudev5mWGBWZIErLB38f7TeN6hV7zof6WBpzMdx/z0
  defer: true
- src: https://cdn.kernvalley.us/js/security.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  defer: true

- src: https://cdn.kernvalley.us/components/leaflet/map.min.js
  referrerPolicy: no-referrer
  crossOrigin: anonymous
  defer: true
- src: /js/index.min.js
  referrerPolicy: no-referrer
  defer: true
