- src: https://unpkg.com/@shgysk8zer0/polyfills@0.6.3/browser.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  integrity: sha384-vx8wPMSS/Ml/fR3V5rbzeTmLKFs+pgzfftsGK3EUEl5HrsWV8DNlfkpqpf6hesKw
  defer: true
- src: /js/index.min.js
  referrerPolicy: no-referrer
  defer: true
- src: https://unpkg.com/@shgysk8zer0/components@0.3.22/leaflet/bundle.min.js
  referrerPolicy: no-referrer
  crossOrigin: anonymous
  integrity: sha384-SQENG/0i6JBMgZBYIb+afNMCXpbn61PZDEuoaPsaw/7CAvEgdmgM8bNGdMebD/6t
  defer: true
