- src: https://cdn.polyfill.io/v3/polyfill.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  noModule: true
  defer: true
- src: https://unpkg.com/@webcomponents/custom-elements@1.4.2/custom-elements.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  noModule: true
  defer: true
  integrity: sha384-xyhN4T4+9VPh8uXl6uWjGzsqwNXN9C2tla8b6zSrSqYlMFUoeCdoxiEJU0js+GNE
- src: https://unpkg.com/@shgysk8zer0/polyfills@0.0.8/all.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  integrity: sha384-v+BhQM1c97/28YXILSO+e6fOcrvW/2gOeNCw6NjBTomnZCGE6UbsaLlL03UU/emh
  defer: true
- src: https://unpkg.com/@shgysk8zer0/kazoo@0.0.16/harden.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  integrity: sha384-55L/wO9o0uIVTeubRIDQB4bewfNqyxrj4OXuxlW24NMEk+ioZwMHVw/tFV78mM+k
  defer: true
- src: /js/index.min.js
  referrerPolicy: no-referrer
  defer: true
- src: https://unpkg.com/@shgysk8zer0/components@0.0.9/leaflet/map.min.js
  referrerPolicy: no-referrer
  crossOrigin: anonymous
  integrity: sha384-nBvezj/iSzoatR/amD1/t42qZqW/GUr5DYukSjozo/c6ZYsfyYdfUdAOcCmL8s0m
  defer: true
