name: Kern Valley Maps
shortName: KRV Maps
id: KRVMaps
startUrl: /?utm_source=pwa&utm_medium=pwa
version: 3.0.3
lang: en
dir: ltr
display: standalone
orientation: any
description: "Map of the Kern River Valley and surrounding areas"
icons-file: /img/icons.svg
theme:
  color: '#007bff'
  background: '#242424'
icons:
  - src: /img/favicon.svg
    type: image/svg+xml
    sizes: 150x150
    purpose: maskable any
  - src: /img/apple-touch-icon.png
    rel: apple-touch-icon
    type: image/png
    sizes: 180x180
  - src: /img/icon-512.png
    type: image/png
    sizes: 512x512
    purpose: maskable any
  - src: /img/icon-192.png
    type: image/png
    sizes: 192x192
    purpose: maskable any
  - src: /img/icon-96.png
    type: image/png
    sizes: 96x96
    purpose: any
  - src: /img/icon-32.png
    type: image/png
    sizes: 32x32
  - src: /img/icon-16.png
    type: image/png
    sizes: 16x16
screenshots:
  - src: https://i.imgur.com/9maR7jY.jpg
    sizes: 1355x667
    type: image/jepg
  - src: https://i.imgur.com/9maR7jYg.jpg
    sizes: 1024x504
    type: image/jpeg
  - src: https://i.imgur.com/9maR7jYl.jpg
    sizes: 640x315
    type: image/jpeg
  - src: https://i.imgur.com/9maR7jYm.jpg
    sizes: 320x158
    type: image/jpeg
  - src: https://i.imgur.com/9maR7jYt.jpg
    sizes: 160x79
    type: image/jpeg
# https://web.dev/app-shortcuts/
shortcuts:
  - name: Kernville
    description: Open map in Kernville
    url: '/?utm_source=shortcut&utm_medium=pwa#kernville'
    icons:
      - src: /img/icon-192.png
        type: image/png
        sizes: 192x192
        purpose: maskable any
      - src: /img/icon-96.png
        type: image/png
        sizes: 96x96
        purpose: any
      - src: /img/icon-32.png
        type: image/png
        sizes: 32x32
  - name: Lake Isabella
    description: Open map in Lake Isabella
    url: '/?utm_source=shortcut&utm_medium=pwa#lake-isabella'
    icons:
      - src: /img/icon-192.png
        type: image/png
        sizes: 192x192
        purpose: maskable any
      - src: /img/icon-96.png
        type: image/png
        sizes: 96x96
        purpose: any
      - src: /img/icon-32.png
        type: image/png
        sizes: 32x32
  - name: Wofford Heights
    description: Open map in Wofford Heights
    url: '/?utm_source=shortcut&utm_medium=pwa#wofford-heights'
    icons:
      - src: /img/icon-192.png
        type: image/png
        sizes: 192x192
        purpose: maskable any
      - src: /img/icon-96.png
        type: image/png
        sizes: 96x96
        purpose: any
      - src: /img/icon-32.png
        type: image/png
        sizes: 32x32
  - name: Weldon
    description: Open map in Weldon
    url: '/?utm_source=shortcut&utm_medium=pwa#weldon'
    icons:
      - src: /img/icon-192.png
        type: image/png
        sizes: 192x192
        purpose: maskable any
      - src: /img/icon-96.png
        type: image/png
        sizes: 96x96
        purpose: any
      - src: /img/icon-32.png
        type: image/png
        sizes: 32x32
related_applications:
  - platform: webapp
    url: https://maps.kernvalley.us/webapp.webmanifest
  - platform: play
    id: com.krv_maps.twa
    url: https://play.google.com/store/apps/details?id=com.krv_maps.twa
file_handlers:
  - action: /
    accept:
      application/geo+json:
        - .geojson
protocol_handlers:
  - protocol: geo
    url: /?geo=%s
  - protocol: web+geo
    url: /?geo=%s
  - protocol: web+krvplace
    url: /?place=%s
features:
  - Offline map of the Kern River Valley
  - Lists businesses, restaurants, campgrounds, gas stations, and more
  - Quickly search for places by name
  - Find information such as addresses, phone numbers, and websites
  - Mark your location on the map and see nearby places
  - Easily find and share places
  - 235+ places marked including restaurants, campgrounds, motels, schools, and landmarks
  # - Support for opening GeoJSON files
# https://github.com/w3c/manifest/wiki/Categories
categories:
  - business
  - productivity
  - utilities
  - travel
  - navigation
